services:
  coursemapping-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=coursemappingdb;Username=jazza;Password=JasGres
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - seq
      - postgres
    profiles:
      - void

  postgres:
    image: postgres:latest
    container_name: coursemapping-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=JasGres
    ports:
      - "6789:5432"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5100:80"

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__CourseMappingDb=Server=postgres;Port=5432;Database=coursemappingdb;User Id=postgres;Password=JasGres
    depends_on:
      - postgres
    command: >
      dotnet test CourseMapping.Domain.Tests.UnitTests/CourseMapping.Domain.Tests.UnitTests.csproj --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory /app/test-results/unit
    volumes:
      - ./test-results/unit:/app/test-results/unit

  test-component:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__CourseMappingDb=Server=postgres;Port=5432;Database=coursemappingdb;User Id=postgres;Password=JasGres
    depends_on:
      - postgres
    command: >
      dotnet test CourseMapping.Tests.ComponentTests/CourseMapping.Tests.ComponentTests.csproj --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory /app/test-results/component
    volumes:
      - ./test-results/component:/app/test-results/component

  test-integration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__CourseMappingDb=Server=postgres;Port=5432;Database=coursemappingdb;User Id=postgres;Password=JasGres
    depends_on:
      - postgres
    command: >
      dotnet test CourseMapping.Tests.IntegrationTests/CourseMapping.Tests.IntegrationTests.csproj --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory /app/test-results/integration
    volumes:
      - ./test-results/integration:/app/test-results/integration
